# Generated by Django 3.1.1 on 2020-09-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_of_photos',
            field=models.IntegerField(default=0),
        ),
    ]
