# Generated by Django 3.1.1 on 2020-09-29 08:41

import django.core.validators
from django.db import migrations, models
import mainapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200929_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), mainapp.validators.file_size_validator]),
        ),
    ]
