# Generated by Django 3.1.1 on 2020-10-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20201002_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_name',
            field=models.CharField(max_length=200),
        ),
    ]
