# Generated by Django 3.1.1 on 2020-10-05 16:06

import django.core.validators
from django.db import migrations, models
import mainapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20201003_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='original_photos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), mainapp.validators.file_size_validator]),
        ),
    ]
